name: minio

services:
  minio:
    container_name: ${SERVICE_NAME}
    image: ${DOCKER_IMAGE}
    ports:
      - 9000:${API_PORT}
      - 9001:${DASHBOARD_PORT}
    environment:
      # refs: https://min.io/docs/minio/linux/reference/minio-server/settings/core.html
      - MINIO_DOMAIN=${API_DOMAIN}
      - MINIO_COMPRESSION_ENABLE=on
      - MINIO_COMPRESSION_ALLOW_ENCRYPTION=off
      # refs: https://min.io/docs/minio/linux/reference/minio-server/settings/root-credentials.html
      - MINIO_ROOT_USER=${ADMIN_USER}
      - MINIO_ROOT_PASSWORD=${ADMIN_PASS}
      - MINIO_API_ROOT_ACCESS=on
      # refs: https://min.io/docs/minio/linux/reference/minio-server/settings/console.html
      - MINIO_BROWSER=on
      - MINIO_BROWSER_LOGIN_ANIMATION=off
      - MINIO_BROWSER_REDIRECT=false
      - MINIO_BROWSER_SESSION_DURATION=365d
      # refs: https://min.io/docs/minio/linux/reference/minio-server/minio-server.html
    command: server /data --address=":${API_PORT}" --console-address=":${DASHBOARD_PORT}"
    volumes:
      - ./minio/data:/data
      - ./minio/config:/root/.minio
    extra_hosts:
      - "${API_DOMAIN}:127.0.0.1"
    healthcheck:
        # refs:
        # - https://min.io/docs/minio/linux/reference/minio-mc/mc-ready.html
        # - https://github.com/minio/minio/issues/18389
        test: ["CMD", "mc", "ready", "local"]
        interval: 3s
        timeout: 10s
        retries: 12
